test_case/ritm_style/urls.py
from django.urls import path
from . import views

app_name = "ritm_style"

urlpatterns = [
    path("", views.index, name="index"),
    path("news/", views.news, name="news"),
    path("blog/", views.blog, name="blog"),
    path("new_format", views.new_format, name="new_format"),
]

test_case/test_case/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("ritm_style.urls", namespace="ritm_style")),
    path("admin/", admin.site.urls),
]

test_case/ritm_style/models.py
from django.db import models

# Create your models here.

test_case/ritm_style/views.py
from django.shortcuts import render


def index(request):
    template = "ritm_style/index.html"
    return render(request, template)


def news(request):
    template = "ritm_style/news.html"
    return render(request, template)


def blog(request):
    template = "ritm_style/blog.html"
    return render(request, template)


def new_format(request):
    template = "ritm_style/new_format.html"
    return render(request, template)

test_case/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
  <head>    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" {#href="{%static 'img/fav/fav.ico' %}"#} type="image">
    <link rel="apple-touch-icon" sizes="180x180" {#href="{% static 'img/fav/apple-touch-icon.png' %}"#}>
    <link rel="icon" type="image/png" sizes="32x32" {#href="{% static 'img/fav/favicon-32x32.png' %}"#}>
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/logo.png' %}">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href={% static "css/bootstrap.min.css" %}>
    <link rel="stylesheet" href={% static "css/main.css" %}>
    <script src={% static "js/jquery-3.3.1.min.js" %}></script>
    <script src={% static "js/bootstrap.min.js" %}></script>
    <script src={% static "js/main.js" %}></script>
    <script src={% static "js/process-forms.js" %}></script>
    <title>{% block title %}Заголовок вкладки{% endblock %}</title>
  </head>
  <body>
    <div class="container">
      <header class="border-bottom">
        {% include 'includes/header.html' %}
      </header>
    </div>
    <main> 
      {% block content %}
        Контент
      {% endblock %}
    </main>
    <div class="container">
      <footer class="border-top py-3">
        {% include 'includes/footer.html' %}
      </footer>
    </div>
  </body>
</html>

test_case/templates/includes/blog_panel.html
{% load static %}
<div class="blog_container">
    <div class="row">
      <div class="col-1-2">
        <img class="blog_image" src="{% static 'img/girl_sunset.png' %}" alt="girl_sunset" >
      </div>
      <div class="col-1-2">
        <div style="margin-left: 60px; margin-right: 60px">
          {% include 'includes/text_new_format.txt' %}
          <div class="text-left" style="margin-top: 20px">
            <button type="button" class="btn btn-primary">
              Читать статью
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>

test_case/templates/includes/feedback.html
{% load static %}

  <div class="text-center">
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#feedbackFormModal">
      Записаться на сеанс
    </button>
  </div>

  <div class="modal" id="feedbackFormModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="myModalLabel">Записаться на сеанс</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">

          <form id="feedbackForm" action={% static "php/process.php" %} enctype="multipart/form-data" novalidate>
            <div class="form-row">
              <div class="col-sm-6">
                <div class="form-group">
                  <label for="name" class="control-label">Имя</label>
                  <input id="name" type="text" name="name" class="form-control" value="" placeholder="Имя" minlength="2" maxlength="30" required="required">
                  <div class="invalid-feedback"></div>
                </div>
              </div>
              <div class="col-sm-6">
                <div class="form-group">
                  <label for="email" class="control-label">Email-адрес</label>
                  <input id="email" type="email" name="email" required="required" class="form-control" value="" placeholder="Email-адрес">
                  <div class="invalid-feedback"></div>
                </div>
              </div>
            </div>
            <div class="form-group">
              <label for="message" class="control-label">Сообщение</label>
              <textarea id="message" name="message" class="form-control" rows="3" placeholder="Сообщение"
                maxlength="500" required="required"></textarea>
              <div class="invalid-feedback"></div>
            </div>
            <div class="form-group captcha">
              <img class="img-captcha" src={% static "php/captcha.php" %} data-src={% static "php/captcha.php" %} alt="captcha">
              <div class="btn btn-light refresh-captcha">Обновить</div>
              <div class="form-group">
                <label for="captcha" class="control-label">Код, показанный на изображении</label>
                <input type="text" name="captcha" maxlength="6" required="required" id="captcha" class="form-control captcha" placeholder="******"
                  autocomplete="off" value="">
                <div class="invalid-feedback"></div>
              </div>
            </div>
            <div class="form-group agreement">
              <div class="custom-control custom-checkbox">
                <input type="checkbox" name="agree" class="custom-control-input" id="customCheck">
                <label class="custom-control-label" for="customCheck">Нажимая кнопку, я принимаю условия
                  <a href="#">Пользовательского соглашения</a> и даю своё согласие на обработку моих персональных данных, в соответствии
                  с Федеральным законом от 27.07.2006 года №152-ФЗ «О персональных данных».</label>
              </div>
            </div>
            <div class="alert alert-danger form-error d-none">
              Исправьте данные и отправьте форму ещё раз.
            </div>
            <div class="text-right submit">
              <button type="submit" class="btn btn-primary" disabled="disabled">Отправить сообщение</button>
            </div>
          </form>
          <div class="alert alert-success form-success mb-0 d-none">
            Форма успешно отправлена. Нажмите на
            <a href="#" data-form="#feedbackForm">ссылку</a>, чтобы отправить ещё одно сообщение.
          </div>
        </div>
      </div>
    </div>
  </div>

test_case/templates/includes/footer.html
<p>© 2018-{{ year }} RitmStyle</p>

test_case/templates/includes/header.html
{% load static %}
<nav class="navbar navbar-light navbar-expand-lg">
  <div class="container">
    <a class="navbar-brand" href="/">
      <img src="{% static 'img/logo.png' %}" width="50" height="50" class="d-inline-block align-top" alt="logo">
    </a>
      {% with request.resolver_match.view_name as view_name %}
      <div class="container">
        <ul>
          <li style="display: inline-block">
            <a class="nav-link {% if view_name  == 'index' %}active{% endif %}"
              href="{% url 'ritm_style:index' %}">Главная</a>
          </li>
          <li style="display: inline-block"> 
            <a class="nav-link {#{% if view_name  == 'index' %}active{% endif %}#}"
              {#href="{% url 'ritm_style:index' %}"#}>Сеансы</a>
          </li>
          <li style="display: inline-block"> 
            <a class="nav-link {#{% if view_name  == 'index' %}active{% endif %}#}"
              {#href="{% url 'ritm_style:index' %}"#}>Отзывы</a>
          </li>
          <li style="display: inline-block"> 
            <a class="nav-link {#{% if view_name  == 'index' %}active{% endif %}#}"
              {#href="{% url 'ritm_style:index' %}"#}>Контакты</a>
          </li>
          <li style="display: inline-block"> 
            <a class="nav-link {% if view_name  == 'news' %}active{% endif %}"
              href="{% url 'ritm_style:news' %}">Новости</a>
          </li>
          <li style="display: inline-block"> 
            <a class="nav-link {#{% if view_name  == 'index' %}active{% endif %}#}"
              {#href="{% url 'ritm_style:index' %}"#}>Обо мне</a>
          </li>
          <li style="display: inline-block"> 
            <a class="nav-link {% if view_name  == 'blog' %}active{% endif %}"
              href="{% url 'ritm_style:blog' %}">Блог</a>
          </li>
          <li style="display: inline-block"> 
            {% include 'includes/feedback.html' %}
          </li>
        </ul>
      </div>
      {% endwith %}
    </div>
  </div>
</nav>

test_case/templates/includes/href_new_format.html
{% load static %}
<a class="navbar-brand" href="{% url 'ritm_style:new_format' %}">
  <div class="image2">
    <img src="{% static 'img/girl_under_water.png' %}" style="filter: opacity(15%)" width="100%" alt="girl_under_water">
    <h3><span>Новый формат сеансов</span></h3>
  </div>
</a>

test_case/templates/ritm_style/blog.html
{% extends 'base.html' %}
{% block title %}Блог{% endblock %}

{% block content %}
<div class="container py-5">     
  <h1 align="center">Блог</h1>
  <div>
    {% include 'includes/blog_panel.html' %}
  </div>
  <div>
    {% include 'includes/blog_panel.html' %}
  </div>
</div>
{% endblock %}

test_case/templates/ritm_style/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Акватерапия RitmStyle{% endblock %}

{% block content %}
  <div class="container py-5" align="center">
    <div class="image">
      <img src="{% static 'img/girl.png' %}" style="filter: opacity(50%)" width="100%" alt="girl">
      <h2><span>Акватерапия</br>RitmStyle</span></h2>
    </div>
  </div>  
{% endblock %}

test_case/templates/ritm_style/new_format.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Новый формат сеансов{% endblock %}

{% block content %}
<div class="container py-5">     
  <h1 align="center">Новый формат сеансов</h1>
  <div class="container">
    <div class="row">
      <div class="col-1-2">
        <div style="margin-right: 70px">
          {% include 'includes/text_new_format.txt' %}
        </div>
      </div>
      <div class="col-1-2">
        <img src="{% static 'img/girl_sunset.png' %}" alt="girl_sunset" style="float:right;width: 100%">
      </div>
    </div>
  </div>
</div>
{% endblock %}

test_case/templates/ritm_style/news.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Новости{% endblock %}

{% block content %}
<div class="container py-5">
  <h1 align="center">Новости</h1>
  <table>
    <tbody>
      <tr>
        <td>
          {% include 'includes/href_new_format.html' %}
        </td>
        <td>
          {% include 'includes/href_new_format.html' %}
        </td>
        <td>
          {% include 'includes/href_new_format.html' %}
        </td>
      </tr>
      <tr>
        <td>
          {% include 'includes/href_new_format.html' %}
        </td>
        <td>
          {% include 'includes/href_new_format.html' %}
        </td>
        <td>
          {% include 'includes/href_new_format.html' %}
        </td>
      </tr>
    </tbody>
  </table>
</div>
{% endblock %}